### ISSUE TITLE
Add more google domains.

### ISSUE THREAD

**Issue by vitkrv** [techsin/SoRatings#1]
I can't use your extension in my country, because my local google URL is _google.com.ua_. Could you add more URLs in the whitelist? Big thx.

**Comment by techsin** [comment]
Yes, this is the feedback i needed. Consider it done by today

**Comment by techsin** [comment]
changes should show up within few hours let me know if it doesnt work.

**Comment by vitkrv** [comment]
It works fine. Big thx
